framework:
  secret: secret
  router:
    resource: "%kernel.project_dir%/app/routing.yml"
  test: ~
  translator: ~
  default_locale: en
  session:
    storage_id: session.storage.filesystem

twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'

services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  # makes classes in src/AppBundle available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  BabDev\PagerfantaTestBundle\:
    resource: '../src/BabDev/PagerfantaTestBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../src/BabDev/PagerfantaTestBundle/{Tests}'

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  BabDev\PagerfantaTestBundle\Controller\:
    resource: '../src/BabDev/PagerfantaTestBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  pagerfanta.view.my_view_1:
    class: Pagerfanta\View\OptionableView
    arguments:
      - '@pagerfanta.view.default'
      - { proximity: 2, prev_message: Anterior, next_message: Siguiente }
    public: false
    tags:
      - { name: pagerfanta.view, alias: my_view_1 }
